# -*- coding: utf-8 -*-
"""multi-role-chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u7bp50WaRnRh5elIlcLrDaUZwaGG8Xrw
"""

# ==========================================
# 🤖 Gradio Chatbot (Final Working Version)
# ==========================================
import gradio as gr
from openai import OpenAI
import os

# -------------------------------
# 🔐 API Connection
# -------------------------------
api_key =os.getenv("OPENROUTER_API_KEY")
base_url = "https://openrouter.ai/api/v1"
client = OpenAI(base_url=base_url, api_key=api_key)

# -------------------------------
# 🎭 Roles, Styles, Lengths
# -------------------------------
chatbot_roles = {
    "teacher": "You are a teacher who explains things clearly.",
    "friend": "You are a friend who listens and supports the user.",
    "advisor": "You are an advisor who offers practical guidance.",
    "casual": "You are a chatbot that speaks naturally.",
    "mentor": "You are a career mentor who gives advice."
}

chat_styles = {
    "formal": "Speak politely and use professional language.",
    "friendly": "Speak warmly and casually with emojis 😊.",
    "sarcastic": "Use light sarcasm and humor 😏.",
    "poetic": "Respond creatively and use expressive language 🎭."
}

reply_length = {
    "detailed": "Give a detailed answer with explanation of 5–6 lines.",
    "short": "Give a concise answer not more than 2 lines."
}

# -------------------------------
# 🧠 Chat Function
# -------------------------------
def chatbot_response(message, history, role, style, length):
    # System prompt (role + style + reply length)
    system_prompt = f"{chatbot_roles[role]} {chat_styles[style]} {reply_length[length]}"

    # Convert Gradio chat history (list of [user, bot]) to OpenAI message format
    messages = [{"role": "system", "content": system_prompt}]
    for user_msg, bot_msg in history[-6:]:  # limit memory
        messages.append({"role": "user", "content": user_msg})
        messages.append({"role": "assistant", "content": bot_msg})

    # Add current user message
    messages.append({"role": "user", "content": message})

    # Get model response
    response = client.chat.completions.create(
        model="mistralai/mistral-7b-instruct",
        messages=messages
    )

    # Return only the text (string)
    reply = response.choices[0].message.content.strip()
    return reply

# -------------------------------
# 🎨 Gradio UI
# -------------------------------
with gr.Blocks(theme=gr.themes.Soft(primary_hue="indigo")) as demo:
    gr.Markdown("## 🤖 Multi-Role Chatbot (Working Version)\nChat naturally — press **Enter** to send!")

    with gr.Row():
        role_dropdown = gr.Dropdown(choices=list(chatbot_roles.keys()), value="casual", label="Role")
        style_dropdown = gr.Dropdown(choices=list(chat_styles.keys()), value="friendly", label="Style")
        length_dropdown = gr.Dropdown(choices=list(reply_length.keys()), value="detailed", label="Reply Length")

    # ✅ clear_btn removed (Gradio includes it by default)
    chat = gr.ChatInterface(
        fn=chatbot_response,
        additional_inputs=[role_dropdown, style_dropdown, length_dropdown],
        title="AI Chatbot 💬",
        textbox=gr.Textbox(placeholder="Type your message and press Enter...", show_label=False)
    )

demo.launch(share=True)